# Generated by Django 5.2.6 on 2025-12-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterModelOptions(
            name='querylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='querylog',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Average similarity score of retrieved documents', null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='is_answered',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the query was successfully answered'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='num_docs_retrieved',
            field=models.IntegerField(blank=True, help_text='Number of documents retrieved for this query', null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='program_mentioned',
            field=models.CharField(blank=True, db_index=True, help_text='Academic program mentioned in query (e.g., CS, BBA, Engineering)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='query_category',
            field=models.CharField(blank=True, db_index=True, help_text='Query category (e.g., Admission, Fees, Courses, Facilities)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique session identifier for tracking user conversations', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='user_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='Anonymous user identifier (hashed IP or user ID)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='user_rating',
            field=models.IntegerField(blank=True, help_text='User feedback rating (1-5 stars or 0/1 for thumbs down/up)', null=True),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['-created_at'], name='chatbot_que_created_bfe57c_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['session_id', '-created_at'], name='chatbot_que_session_a1edeb_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['program_mentioned', '-created_at'], name='chatbot_que_program_2d0107_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['query_category', '-created_at'], name='chatbot_que_query_c_ce3944_idx'),
        ),
    ]
