# Generated by Django 5.2.6 on 2026-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_delete_document_alter_querylog_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='querylog',
            name='chatbot_que_program_2d0107_idx',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='program_mentioned',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='user_rating',
        ),
        migrations.AlterField(
            model_name='querylog',
            name='query_category',
            field=models.CharField(blank=True, db_index=True, help_text='Query category (see chatbot/utils/analytics.py)', max_length=50, null=True),
        ),
    ]
